### ISSUE TITLE
missing: Backport script

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/bitcoin-maintainer-tools#11]
It would be useful to have the backport script in this repo. I think there are two floating around, but they need to be submitted by the original author with a license.

cc @luke-jr

**Comment by laanwj** [comment]
I've uploaded my backport script here: https://gist.github.com/laanwj/d959545e60401d82c898370f6c34b02d

Not sure it's useful to anyone else but seems to work for me. If so we can add it to the repo.
