### ISSUE TITLE
`github-merge.py` cannot merge PRs with empty body

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/bitcoin-maintainer-tools#111]
While merging https://github.com/bitcoin/bitcoin/pull/22921 with `github-merge.py` I got the following error
```
Warning: unable to retrieve pull information from github: 'NoneType' object is not iterable
```
It turns out that when there is no PR body, `rec['body']` is `None`, not the empty string. We should handle this, probably, or at the least give a better error.

**Comment by prayank23** [comment]
Can be fixed by this:

```diff
def sanitize_ghdata(rec):

    if 'title' in rec: # only for PRs
        rec['title'] = sanitize(rec['title'], newlines=False)
+       if (rec['body']== None):
+           rec['body'] = ""
    rec['body'] = sanitize(rec['body'], newlines=True)

    # "Github username may only contain alphanumeric characters or hyphens'.
    # Use \Z instead of $ to not match final newline only end of string.
    if not re.match('[a-zA-Z0-9-]+\Z', rec['user']['login'], re.DOTALL):
        raise ValueError('Github username contains invalid characters: {}'.format(sanitize(rec['user']['login'])))
    return rec
```

**Comment by laanwj** [comment]
Sure, some comments:

- Move the `if` up a nesting level, to the outer scope of the function. Otherwise it only gets executed if there is a 'tittle' which is an unrelated field
- No `(`…`)` are needed around an if in Python
- Please use `is` to compare against None (object identity comparison)
