### ISSUE TITLE
Feature request: See which PRs conflict before merging

### ISSUE THREAD

**Issue by sanket1729** [bitcoin-core/bitcoin-maintainer-tools#143]
It would like nice if we somehow know which PRs would require a rebase before pushing a merge commit to the master branch. This can help avoid pushing refactors that would break other large PR that is almost ready to merge.

**Comment by sanket1729** [comment]
Similar to the bot in bitcoin/bitcoin repo, but shows the same thing before signing and pushing

**Comment by MarcoFalke** [comment]
This is relatively expensive to calculate, as it requires to iterate over all open pull requests. My suggestion would be to just calculate the conflicts with a separate script and then share them in a comment, like the bot.

**Comment by katesalazar** [comment]
"the simplest command sequence is to run git merge --no-commit, save exit
status, then run git merge --abort"

https://stackoverflow.com/a/46694028

**Comment by sanket1729** [comment]
> This is relatively expensive to calculate, as it requires to iterate over all open pull requests. My suggestion would be to just calculate the conflicts with a separate script and then share them in a comment, like the bot.


Thanks a lot for the response.

**Comment by MarcoFalke** [comment]
You can use https://github.com/MarcoFalke/DrahtBot/blob/main/scripts/conflicts.py if you want (at your own risk)
