### ISSUE TITLE
guix-verify: (docs) needs updating

### ISSUE THREAD

**Issue by fanquake** [bitcoin-core/bitcoin-maintainer-tools#151]
The docs (in README.md) here still refer to gitian.sigs (archived).
The docs refer to `bitcoin/contrib/builder-keys/keys.txt` which no-longer exists. Replaced primarily by: https://github.com/bitcoin-core/guix.sigs/tree/main/builder-keys.

**Comment by laanwj** [comment]
i think the script is useful to see the details about signatures and potential problems with them in a table (besides just verififying downloaded binaries). But if no one is using it, seems also fine with me to remove it.

**Comment by laanwj** [comment]
i've come to agree it's better to remove this script, i think the approach in bitcoin-core/guix.sigs#1207 which makes something similar run in the CI on guix.sigs directly and display it on github is better.

**Comment by fanquake** [comment]
Sounds good to me.
