### ISSUE TITLE
github-merges.py should strip all `@` mentions

### ISSUE THREAD

**Issue by jnewbery** [bitcoin-core/bitcoin-maintainer-tools#30]
github-merges.py creates a merge commit that includes the PR description and any ACKs. If either of those contain `@` mentions, then the merge commit will contain an `@` that will cause notifications for the user whenever the merge commit is cherrypicked into other projects.

github-merges should strip out the `@` character from the commit log it creates.

**Comment by MarcoFalke** [comment]
This would make merge logs of e.g. https://github.com/bitcoin/bitcoin/pull/16439 unreadable

**Comment by sipa** [comment]
What are "merge logs"?

**Comment by MarcoFalke** [comment]
The body of a merge commit that was created with github-merge.py

**Comment by sipa** [comment]
The script could check if what follows is a GitHub username?

I agree that's making things less trivial...

**Comment by fanquake** [comment]
I think maintainers should at least check the PR body and strip any @mentions before merging? 

Adding more calls to GitHub (to lookup usernames?) and modifying the PR body before merging doesn't seem ideal. If anything, maybe the script could just fail (in the hopefully unlikely, i.e #16439), case where it does find an actual `@`. Then the maintainer can either check and modify or pass a `--merge-with-@s` etc.

**Comment by MarcoFalke** [comment]
I think printing a warning is enough, similar to the warning when merged without any review

**Comment by laanwj** [comment]
> I think printing a warning is enough, similar to the warning when merged without any review

Agree that a warning is the way to go here. The merger might or might not want to continue, or first edit the PR opening post.

**Comment by fanquake** [comment]
Opened a PR to warn about @s in #32.
