### ISSUE TITLE
Strip redacted ACKs from merge commits?

### ISSUE THREAD

**Issue by fanquake** [bitcoin-core/bitcoin-maintainer-tools#40]
In https://github.com/bitcoin/bitcoin/pull/17074

```bash
ACKs for top commit:
  laanwj:
    ~~ACK dd85166~~
```

Should we include these, strip them out? Maybe it doesn't matter etc.

**Comment by laanwj** [comment]
I don't think it's wrong to include disagreement.

Though in this particular case I redacted that ACK wrongly. I thought I saw a problem but it turned out to be perfectly ok.
