### ISSUE TITLE
tACK in "GitHub review" not counted in GitHub merge

### ISSUE THREAD

**Issue by jonasschnelli** [bitcoin-core/bitcoin-maintainer-tools#42]
The following tACK was not recognised by our GitHub merge script:
https://github.com/bitcoin/bitcoin/pull/15084#pullrequestreview-190732482

**Comment by laanwj** [comment]
It looks like it refers to a different commit ID than the one that was merged? If so, this is intentional, it counts only ACKs on what was exactly merged.

**Comment by MarcoFalke** [comment]
Yes, this is a feature

**Comment by jonasschnelli** [comment]
Oh. I see. Thanks for closing.
