### ISSUE TITLE
Filter duplicate ACKs from merge commits

### ISSUE THREAD

**Issue by fanquake** [bitcoin-core/bitcoin-maintainer-tools#46]
i.e in https://github.com/bitcoin/bitcoin/commit/4fb82e916b3b92c14443db23d7f606eb02cf1654 after merging https://github.com/bitcoin/bitcoin/pull/17567. This probably happens so rarely that it doesn't matter.

```bash
ACKs for top commit:
  jonasschnelli:
    utACK 27d82b6
  jonasschnelli:
    Tested ACK 27d82b6 - successfully compiled on 10.15.1
```

**Comment by laanwj** [comment]
Heh, one ACK per person (the most recent one) seems to be enough
