### ISSUE TITLE
ghwatch: Notification reason priority sorting

### ISSUE THREAD

**Issue by laanwj** [bitcoin-core/bitcoin-maintainer-tools#80]
I think it would be useful to have an sorting mode that first sorts by specificity (based on notification reason), and only then by time. This would make sure that important notifications appear on top, and are not crowded out by spammy subscription notifications.

Example order:

- `assign` (highest prioroty)
- `review requested`
- `mention`
- `author`
- `comment`
- …
- `subscribed` (lowest priority)

**Comment by jonatack** [comment]
Great idea -- was about to suggest something like this.
