### ISSUE TITLE
gitian-verify.py: gpg --verify extremely slow for unknown keys on macOS 11.3

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/bitcoin-maintainer-tools#95]
See #94

**Comment by Sjors** [comment]
Rebasing after #90 didn't help, but I'll have it try a bit longer...

**Comment by Sjors** [comment]
Ok, this just takes _really_ long... (10+ minutes on a 2019 Macbook Pro with 8 CPU's)...

**Comment by Sjors** [comment]
Aha, maybe the problem is the missing key. @laanwj can we detect this separately?

<img width="584" alt="Schermafbeelding 2021-05-02 om 17 09 40" src="https://user-images.githubusercontent.com/10217/116817974-3ee45800-ab69-11eb-8e3a-432c3e73b152.png">

**Comment by coinforensics** [comment]
Could replicate the problem on my MacBook Air (2014) with missing keys.

If I imported all the missing keys to the GPG Keychain it took only a couple of seconds.

**Comment by laanwj** [comment]
Any idea *what* is taking so long on missing keys? I do not have this problem on Linux.

Is it trying to connect to the internet or something?

**Comment by Sjors** [comment]
I really hope it's not spontaneously connecting to the internet every time I verify a signature. I should doublecheck for NSA malware :-)

**Comment by laanwj** [comment]
I know you're joking but even without NSA malware it's not unheard of—e.g. TLS certificate expiration checking has an active component.
Not necessarily saying that it is this, but long delays that do not involve 100% CPU use tend to be I/O based. A maybe more realistic in this case possibility is a local service (e.g. smartcard daemon) that cannot be contacted.

**Comment by coinforensics** [comment]
It tries to connect to the internet if the key is missing in the GPG Keychain.

I think it is gpgme trying via dirmngr to get the missing key or check for OCSP.

![gitian-verify-dirmngr](https://user-images.githubusercontent.com/59567284/116866219-51af6900-ac0b-11eb-9532-09a1b452e73d.png)

**Comment by coinforensics** [comment]
I created a pull request with the offline flag set to prevent network connections.

This should solve this problem.

Or is this too strict?

**Comment by githubnew-pro** [comment]
> [شماره 94 را](https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/94) ببینید[](https://github.com/bitcoin-core/bitcoin-maintainer-tools/pull/94)
